[env:GaulixLCrp2040V1b]
extends = rp2040_base
board = rpipico
upload_protocol = picotool
# add our variants files to the include and src paths
build_flags = ${rp2040_base.build_flags}
              -DRPI_PICO
              -Ivariants/GaulixLCrp2040V1b
              -DDEBUG_RP2040_PORT=Serial
              -DHW_SPI1_DEVICE
              -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m0plus"
              -DUSERPREFS_CHANNELS_TO_WRITE=2
              -DUSERPREFS_CHANNEL_0_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_0_NAME=\"Fr_Balise\"
              -DUSERPREFS_CHANNEL_0_PRECISION=32
              -DUSERPREFS_CHANNEL_0_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_0_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_1_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_1_NAME=\"Fr_EMCOMM\"
              -DUSERPREFS_CHANNEL_1_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_1_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_2_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_2_NAME=\"Fr_BlaBla\"
              -DUSERPREFS_CHANNEL_2_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_2_UPLINK_ENABLED=true
              -DUSERPREFS_LORACONFIG_HOP_LIMIT=3
              -DUSERPREFS_CONFIG_LORA_OK_TO_MQTT=true
              -DUSERPREFS_CONFIG_LORA_IGNORE_MQTT=true
              -DUSERPREFS_CONFIG_LORA_REGION=meshtastic_Config_LoRaConfig_RegionCode_EU_868
              -DUSERPREFS_CONFIG_DEVICE_INTERVAL=43200
              -DUSERPREFS_CONFIG_SMART_POSITION_ENABLED=false
              -DUSERPREFS_CONFIG_POSITION_INTERVAL=86400
              -DUSERPREFS_TELEMETRY_DEVICE_INTERVAL=7200
              -DUSERPREFS_TELEMETRY_ENVIRONMENT_ENABLED=false
              -DUSERPREFS_TELEMETRY_ENVIRONMENT_INTERVAL=21600
              -DUSERPREFS_TELEMETRY_AIR_QUALITY_ENABLED=false
              -DUSERPREFS_TELEMETRY_AIR_QUALITY_INTERVAL=86400
              -DUSERPREFS_NEIGHBOR_INFO_ENABLED=true
              -DUSERPREFS_NEIGHBOR_INFO_INTERVAL=43200
              -DUSERPREFS_CONFIG_DEVICE_ROLE=meshtastic_Config_DeviceConfig_Role_CLIENT
              -DUSERPREFS_LORACONFIG_CHANNEL_NUM=1
              -DUSERPREFS_LORACONFIG_MODEM_PRESET=meshtastic_Config_LoRaConfig_ModemPreset_LONG_MODERATE
debug_build_flags = ${rp2040_base.build_flags}, -g
debug_tool = cmsis-dap ; for e.g. Picotool