[env:GaulixLCrp2040V1b-chamrousse]
extends = rp2040_base
board = rpipico
upload_protocol = picotool
# add our variants files to the include and src paths
build_flags = ${rp2040_base.build_flags}
              -DRPI_PICO
              -Ivariants/GaulixLCrp2040V1b-chamrousse
              -DDEBUG_RP2040_PORT=Serial
              -DHW_SPI1_DEVICE
              -L "${platformio.libdeps_dir}/${this.__env__}/bsec2/src/cortex-m0plus"
              -DMESHTASTIC_EXCLUDE_AUDIO=1
              -DMESHTASTIC_EXCLUDE_DETECTIONSENSOR=1
              -DMESHTASTIC_EXCLUDE_RANGETEST=1
              -DMESHTASTIC_EXCLUDE_ATAK=1
              -DMESHTASTIC_EXCLUDE_INPUTBROKER=1
              -DMESHTASTIC_EXCLUDE_HEALTH_TELEMETRY=1
              -DMESHTASTIC_EXCLUDE_WIFI=1
              -DMESHTASTIC_EXCLUDE_SCREEN=1
              -DMESHTASTIC_EXCLUDE_POWER_FSM=1
              -DMESHTASTIC_EXCLUDE_EXTERNALNOTIFICATION=1
              -DMESHTASTIC_EXCLUDE_PAXCOUNTER=1
              -DMESHTASTIC_EXCLUDE_CANNEDMESSAGES=1
              -DMESHTASTIC_EXCLUDE_WAYPOINT=1
              -DMESHTASTIC_EXCLUDE_MQTT=1
              -DMESHTASTIC_EXCLUDE_BLUETOOTH=1
              -DMESHTASTIC_EXCLUDE_TEXTMESSAGE=1
              -DMESHTASTIC_EXCLUDE_WEBSERVER=1
              -DMESHTASTIC_EXCLUDE_POWERMON=1
              -DEXCLUDE_POWER_FSM=1
              -DUSERPREFS_CHANNELS_TO_WRITE=6
              -DUSERPREFS_CHANNEL_0_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_0_NAME=\"Fr_Balise\"
              -DUSERPREFS_CHANNEL_0_PRECISION=32
              -DUSERPREFS_CHANNEL_0_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_0_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_1_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_1_NAME=\"Fr_EMCOMM\"
              -DUSERPREFS_CHANNEL_1_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_1_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_2_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_2_NAME=\"Fr_BlaBla\"
              -DUSERPREFS_CHANNEL_2_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_2_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_3_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_3_NAME=\"LongMod\"
              -DUSERPREFS_CHANNEL_3_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_3_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_4_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_4_NAME=\"France\"
              -DUSERPREFS_CHANNEL_4_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_4_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_5_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_5_NAME=\"R_ARA\"
              -DUSERPREFS_CHANNEL_5_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_5_UPLINK_ENABLED=true
              -DUSERPREFS_CHANNEL_6_DOWNLINK_ENABLED=false
              -DUSERPREFS_CHANNEL_6_NAME=\"LongFast\"
              -DUSERPREFS_CHANNEL_6_PSK={0xd4,0xf1,0xbb,0x3a,0x20,0x29,0x07,0x59,0xf0,0xbc,0xff,0xab,0xcf,0x4e,0x69,0x01}
              -DUSERPREFS_CHANNEL_6_UPLINK_ENABLED=true
              -DUSERPREFS_LORACONFIG_HOP_LIMIT=3
              -DUSERPREFS_CONFIG_LORA_OK_TO_MQTT=true
              -DUSERPREFS_CONFIG_LORA_IGNORE_MQTT=true
              -DUSERPREFS_CONFIG_LORA_REGION=meshtastic_Config_LoRaConfig_RegionCode_EU_868
              -DUSERPREFS_CONFIG_OWNER_LONG_NAME=\"38CHAMLM8ClN\"
              -DUSERPREFS_CONFIG_OWNER_SHORT_NAME=\"38CM\"
              -DUSERPREFS_CONFIG_DEVICE_INTERVAL=43200
              -DUSERPREFS_CONFIG_SMART_POSITION_ENABLED=false
              -DUSERPREFS_CONFIG_POSITION_INTERVAL=86400
              -DUSERPREFS_FIXED_GPS=\"\"
              -DUSERPREFS_FIXED_GPS_ALT=1700
              -DUSERPREFS_FIXED_GPS_LAT=45.125794
              -DUSERPREFS_FIXED_GPS_LON=5.87306
              -DUSERPREFS_TELEMETRY_DEVICE_INTERVAL=7200
              -DUSERPREFS_TELEMETRY_ENVIRONMENT_ENABLED=false
              -DUSERPREFS_TELEMETRY_ENVIRONMENT_INTERVAL=21600
              -DUSERPREFS_TELEMETRY_AIR_QUALITY_ENABLED=false
              -DUSERPREFS_TELEMETRY_AIR_QUALITY_INTERVAL=86400
              -DUSERPREFS_NEIGHBOR_INFO_ENABLED=true
              -DUSERPREFS_NEIGHBOR_INFO_INTERVAL=43200
              -DUSERPREFS_CONFIG_DEVICE_ROLE=meshtastic_Config_DeviceConfig_Role_CLIENT
              -DUSERPREFS_DEVICE_REBROADCAST_MODE=meshtastic_Config_DeviceConfig_RebroadcastMode_CORE_PORTNUMS_ONLY
              -DUSERPREFS_LORACONFIG_CHANNEL_NUM=1
              -DUSERPREFS_LORACONFIG_MODEM_PRESET=meshtastic_Config_LoRaConfig_ModemPreset_LONG_MODERATE
              -DUSERPREFS_TZ_STRING=\"CET-1CEST,M3.5.0,M10.5.0/3\"
              -DUSERPREFS_USE_ADMIN_KEY_0={0x26,0x04,0xdb,0x02,0xbc,0x20,0x2e,0xac,0x20,0x4f,0x4f,0xeb,0xdc,0x4b,0x60,0xfd,0x11,0x31,0xed,0x89,0xc2,0x96,0x27,0xa0,0x01,0x27,0x7d,0xe8,0x74,0x8d,0xef,0x07}
              -DUSERPREFS_USE_ADMIN_KEY_1={0xbc,0x8a,0xbd,0x69,0xea,0x1c,0x2c,0xba,0xfc,0x67,0x1f,0x11,0x2b,0x56,0x7b,0xe0,0xd0,0xb1,0xa8,0x55,0x84,0x2b,0xc0,0x8d,0x84,0x7e,0xd4,0xe8,0x0b,0x04,0xac,0x66}
              -DUSERPREFS_USE_ADMIN_KEY_2={0x57,0x7b,0x11,0xd3,0x55,0x06,0x50,0x46,0x87,0x8d,0x56,0x8e,0xb2,0x82,0x60,0xe0,0x31,0x4b,0x2f,0x35,0x64,0x49,0x17,0x7c,0x9c,0x70,0x1f,0x29,0xa2,0x56,0xbc,0x5b}
debug_build_flags = ${rp2040_base.build_flags}, -g
debug_tool = cmsis-dap ; for e.g. Picotool